//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bruno_Daniel_Stand
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarroVenda : Carro
    {
        public string Extras { get; set; }
        public Nullable<int> VendaIdVenda { get; set; }
    
        public virtual Venda Venda { get; set; }
    }
}
